### ISSUE TITLE
Facing issue while using get method of dataset with casting

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#1]
There seems to be an issue/mis-interpretation with the parsing of the column in the dataset.

Like: I have a dataset like this:
DatSet d = N.newDataSet(N.asList("id"),N.asList(N.asList("101"), N.asList("102")));

When I try,
1. d.get(Long.class, "id")
2.  d.getLong("id")

Both of above fails, even though id column data is parsable to long type.

I found, you are trying to get longValue of that object, but in case of String this function is not present and things goes wrong.

can you please assist. Thank you

**Comment by landawn** [comment]
Hello, 
There is no underline auto-conversion, by design., because it will be verify inefficient to convert the value for each call  if column size(DataSet size) is big/huge(that's very possible). the specified type is only used to identify the column value and they're should be consistent. if column value is different from target type. you can convert the column values by:
```
dataSet.updateColumn("id", (String value) -> Long.valueOf(value));
```

**Comment by infinite-sahil** [comment]
Then what is the use of this method:
`d.get(Long.class, "id")`

when it can't type cast, it is somehow conveying a wrong perception to the user.

I agree,  this operation might be costly for large dataset, but if somebody still wants it, ready to bear the cost then its looks ok.
Below code also gonna do the same and somehow i have to do this way because i want it in Long format.
dataSet.updateColumn("id", (String value) -> Long.valueOf(value));


Thank you for the reply :)

**Comment by landawn** [comment]
@infinite-sahil 
I see your points. And agree that it confuses people and may be misused. I will deprecate it in next release.  `dataSet.updateColumn("id", (String value) -> Long.valueOf(value))` will be more efficient because it doesn't do type checking(e.g. `instanceof`) for each call, although it may be just a tiny improvement. However high performance/efficient is one of the most important goals of this library. so we care about it. Thanks

**Comment by landawn** [comment]
By the way, you can use method: `<C extends Collection<?>> DataSet newDataSet(Map<String, C> map)` to create your test `DataSet`.  `keys`  are column names, `values` are columns. for example:
```
DataSet ds = N.newDataSet(N.asMap("id", N.asList("101", "102")));
```
Just in case you may need to create more sample `DataSets` in your future tests.

**Comment by infinite-sahil** [comment]
Thank you @landawn for your valuable suggestion :)
I am marking it closed as above answer is acceptable.
