### ISSUE TITLE
Grouping on the basis of one column in dataset and then sorting

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#19]
I have one use-case, where I have dataset and i want to GroupBy on the basis of one column and after grouping by, I want to sort the list of the value for each key.

For example: I have DataSet of Employee with column as ID, NAME, AGE, DEPT_ID?
I want to group by DEP_ID and then sort then by name.

can you please give some example, how can we achieve this with dataset.

Thank you.

**Comment by landawn** [comment]
There is no way to do it in one shot or it could be very complicated in one shot. But you can always do it in two steps: `groupBy` -> sort each value in the target column. Here is the sample:
```
DataSet ds = N.newDataSet(
        N.asLinkedHashMap("ID", N.asList(1, 3, 2, 5, 4), 
                          "NAME", N.asList("Jack", "Tom", "Bill", "Jack", "Joe"), 
                          "AGE", N.asList(30, 50, 51, 20, 30), 
                          "DEPT_ID", N.asList(101, 102, 101, 102, 101)));
ds.println();
//    +----+------+-----+---------+
//    | ID | NAME | AGE | DEPT_ID |
//    +----+------+-----+---------+
//    | 1  | Jack | 30  | 101     |
//    | 3  | Tom  | 50  | 102     |
//    | 2  | Bill | 51  | 101     |
//    | 5  | Jack | 20  | 102     |
//    | 4  | Joe  | 30  | 101     |
//    +----+------+-----+---------+
DataSet groupedResult = ds.groupBy("DEPT_ID", "aggResult", N.asList("ID", "NAME", "AGE"), a -> N.asList(a.clone()), MoreCollectors.toList());

groupedResult.println();
//    +---------+----------------------------------------------+
//    | DEPT_ID | aggResult                                    |
//    +---------+----------------------------------------------+
//    | 101     | [[1, Jack, 30], [2, Bill, 51], [4, Joe, 30]] |
//    | 102     | [[3, Tom, 50], [5, Jack, 20]]                |
//    +---------+----------------------------------------------+

groupedResult.<List<List<Object>>> stream("aggResult").forEach(r -> N.sort(r, Comparators.comparingBy(v -> (String) v.get(1))));
groupedResult.println();
//    +---------+----------------------------------------------+
//    | DEPT_ID | aggResult                                    |
//    +---------+----------------------------------------------+
//    | 101     | [[2, Bill, 51], [1, Jack, 30], [4, Joe, 30]] |
//    | 102     | [[5, Jack, 20], [3, Tom, 50]]                |
//    +---------+----------------------------------------------+
```
I convert the aggregation result value to List by `rowMapper` function: `a -> N.asList(a.clone())` just because I need to print out the result. you can do own conversion or no at all, just using `Object[]`. For Example: 
```
groupedResult = ds.groupBy("DEPT_ID", "aggResult", N.asList("ID", "NAME", "AGE"), MoreCollectors.toList());
groupedResult.<List<Object[]>> stream("aggResult").forEach(r -> N.sort(r, Comparators.comparingBy(v -> (String) v[1])));
```
The code will be very similar if you only want to aggregate on one column `NAME`, not `("ID", "NAME", "AGE")`. But please remember you can only aggregate one/more columns into one result column. please free to ask if that's not extract what you want, or you could also play out by above sample for other scenarios.

**Comment by landawn** [comment]
By the way, I use version 1.7.0 in above sample. please upgrade version 1.7.0. That should be my last major change version.

**Comment by infinite-sahil** [comment]
Thanks a lot @landawn :)

**Comment by infinite-sahil** [comment]
@landawn Just one small doubt:
can you please elaborate bit more on groupBy semantics.

`ds.groupBy("DEPT_ID", "aggResult", N.asList("ID", "NAME", "AGE"), a -> N.asList(a.clone()), MoreCollectors.toList());
`

some quickies:
1. New column name can be same as old one ?
2. What in case i have 100 of columns, and i want to groupBy one column and want 100 columns as out without specifying 100 column in N.asList (i.e. N.asList("ID", "NAME", "AGE"))

**Comment by landawn** [comment]
@infinite-sahil 
1, Yes, since a new `DataSet` will be created by `groupBy`
2, You do not and should not do it by `N.asList("column1", "column2", ... "column100")`. 
You can create `aggColumnNames` with `Seq.filter`, or `Stream.filter`, whatever you would like to, for example:
```
List<String> aggColumnNames = Seq.of(myDataSet.columnNameList()).filter(cn -> cn.startsWith("a"));
```

By the way, a few new methods: `N.sortBy` added in version 1.7.1, above sample by simplified to:
```
groupedResult.<List<Object[]>> stream("aggResult").forEach(r -> N.sortBy(r, v -> (String) v[1]));
```

Sorry for late reply, I just saw this message today.
