### ISSUE TITLE
Question/Issue: Batch insert

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#23]
Hi @landawn 

I am trying to perform batch insert but somehow my data is not getting committed in batches.

Like i have passed SQLExecutor.JdbcSetting with batch size as 1000, but if conn is null then it set autoCommit as false and commit data for all batches at once.

can you please suggest something, I need to finish this part urgently.

Thank you in advance.

**Comment by landawn** [comment]
is the batchInsert executed in any transaction? how did you verify if the records are inserted or not?
Here is a test sample: [SQLExecutorTest](https://github.com/landawn/AbacusUtil/blob/master/samples/com/landawn/samples/abacus/SQLExecutorTest.java). please take a look. if there is anything different from your batch insert code?

**Comment by infinite-sahil** [comment]
Noh, there is no transaction.
records are getting inserted but records of all batches getting inserted at once.

Like i have 10,000 record and my batch size is 1,000, so it should get committed in database in a batch of 1000, but currently 10,000 records are getting inserted in a single go.

**Comment by infinite-sahil** [comment]
code is written in the same way as specified in the SQLExecutorTest.

**Comment by landawn** [comment]
Got it. that's right behavior.

They're not inserted in `single go`. The records are inserted into db batch by batch, but `committed` at the end.  If i understand correctly, `commit` most likely just tell db that update is done, not sending all data to db for update. there is no limit/(performance) impact to records you want to do in batch. you can insert 10,000, 100,000, or even 1 millions records in one `batchInsert` call.

if the size of parameters list is bigger than batch size, yes, the auto commit will be set to false, and commit once at the end of execution. because `batchInsert `is one shot. we can't tell user: your `batchInsret `is failing: 30 records are inserted and committed to db, 70 records not.

**Comment by landawn** [comment]
There is one scenario: huge(>10k or 100k) data import. and you don't want to insert from the begin if it fails. Do this:
```
StreamEx.of(myHugeDataRecordList).split(batchSize)
    .forEach(batchParameters -> sqlExecutor.insert(sql_insert, batchParameters));
```
Or:
```
StreamEx.of(myHugeDataRecordList).split(batchSize)
    .forEach(batchParameters -> {
	try {
	    sqlExecutor.insert(sql_insert, batchParameters);
	} catch (Exception e) {
	    // continue, or mark/save the failed batchParameters for retry? whatever
	}
     }
);
```
